### ISSUE TITLE
Licensing and Maintained Code

### ISSUE THREAD

**Issue by luchini18** [nquesada/symmetry#1]
Hi,
Just wanted to let you know the original author Serguei Patchkovskii has a repository [here](https://github.com/MBI-Theory/symmetry) that contains the GNU license as well as some more recent updates and bug fixes to this original code, in case you wanted to add some reference or at least the license from this repository.

**Comment by nquesada** [comment]
Hi @luchini18 ---- Thanks for making me aware of this! Really happy to see @serguei-patchkovskii has made his code available and is maintaining it. I will update the README to point directly to https://github.com/MBI-Theory/symmetry . The only reason I created this repo is because for a while it was hard to find `symmetry`. Eventually, I will just delete this repo.

**Comment by nquesada** [comment]
Hi have updated the README. If you think it should be changed, please feel free to make a PR.

**Comment by luchini18** [comment]
No worries! I was also using the code from your repository after the original website went down so thanks for making it available! I had reached out to the original author looking for that license and he told me about the repository and wanted to let you know! 
Thanks!
